--테이블 만들기
CREATE TABLE ADDRESS_VO(
NUM NUMBER(3),
NAME VARCHAR2(20),
PHONE VARCHAR2(100),
ADDRESS VARCHAR2(100)
);

--데이터 저장
INSERT INTO ADDRESS_VO (NUM, NAME, PHONE, ADDRESS) VALUES (1, '김', '000-0000-0000', '서울');
INSERT INTO ADDRESS_VO (NUM, NAME, PHONE, ADDRESS) VALUES (2, '최', '111-1111-1111', '경기');
INSERT INTO ADDRESS_VO (NUM, NAME, PHONE, ADDRESS) VALUES (3, '박', '222-2222-2222', '인천');

--데이터 검색
SELECT * FROM ADDRESS_VO;

--데이터 수정
UPDATE ADDRESS_VO SET NUM = 4 WHERE NAME = '최';

--데이터 삭제
DELETE FROM ADDRESS_VO WHERE NAME = '박';
